
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LNE = 28;
  public static final int NUMERO = 3;
  public static final int PP = 19;
  public static final int AB = 20;
  public static final int POR = 16;
  public static final int CHAR = 6;
  public static final int INT = 5;
  public static final int LMAQ = 25;
  public static final int FOR = 35;
  public static final int CP = 11;
  public static final int LME = 26;
  public static final int LMA = 24;
  public static final int DIV = 17;
  public static final int CB = 21;
  public static final int IF = 31;
  public static final int EOF = 0;
  public static final int ASIG = 13;
  public static final int LAND = 29;
  public static final int error = 1;
  public static final int COMA = 18;
  public static final int LOR = 30;
  public static final int ADD = 38;
  public static final int MENOS = 15;
  public static final int IDENT = 2;
  public static final int CLL = 9;
  public static final int ELSE = 32;
  public static final int WHILE = 33;
  public static final int FLOAT = 7;
  public static final int LNEQ = 23;
  public static final int DEL = 39;
  public static final int LEQ = 22;
  public static final int ALL = 8;
  public static final int TEXTO = 4;
  public static final int LMEQ = 27;
  public static final int AP = 10;
  public static final int PRINT = 36;
  public static final int DO = 34;
  public static final int SET = 37;
  public static final int PYC = 12;
  public static final int MAS = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENT",
  "NUMERO",
  "TEXTO",
  "INT",
  "CHAR",
  "FLOAT",
  "ALL",
  "CLL",
  "AP",
  "CP",
  "PYC",
  "ASIG",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "COMA",
  "PP",
  "AB",
  "CB",
  "LEQ",
  "LNEQ",
  "LMA",
  "LMAQ",
  "LME",
  "LMEQ",
  "LNE",
  "LAND",
  "LOR",
  "IF",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "PRINT",
  "SET",
  "ADD",
  "DEL"
  };
}

