// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: PLXC.flex

import java_cup.runtime.*;


// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class Yylex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\2\2\22\0\1\1\1\4"+
    "\4\0\1\5\1\6\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\11\20\1\21\1\22\1\23"+
    "\1\24\1\25\2\0\4\26\1\27\25\26\1\30\1\0"+
    "\1\31\3\0\1\32\1\26\1\33\1\34\1\35\1\36"+
    "\1\26\1\37\1\40\2\26\1\41\1\26\1\42\1\43"+
    "\1\44\1\26\1\45\1\46\1\47\2\26\1\50\3\26"+
    "\1\51\1\52\1\53\7\0\1\3\u01a2\0\2\3\326\0"+
    "\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\2\1\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\1\1\12\2\13\1\14\1\15"+
    "\1\16\1\17\1\20\2\21\1\22\1\23\10\21\1\24"+
    "\1\1\1\25\1\26\1\27\1\30\1\0\1\13\1\2"+
    "\2\0\1\31\1\32\1\33\1\0\1\21\1\34\3\21"+
    "\1\35\4\21\1\36\1\13\1\37\1\40\3\21\1\41"+
    "\1\42\1\21\1\43\1\21\1\44\1\45\3\21\1\46"+
    "\1\47\1\50";

  private static int [] zzUnpackAction() {
    int [] result = new int[78];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\54\0\54\0\130\0\204\0\260\0\54\0\54"+
    "\0\54\0\54\0\54\0\54\0\334\0\u0108\0\u0134\0\u0160"+
    "\0\54\0\54\0\u018c\0\u01b8\0\u01e4\0\u0210\0\u023c\0\54"+
    "\0\54\0\u0268\0\u0294\0\u02c0\0\u02ec\0\u0318\0\u0344\0\u0370"+
    "\0\u039c\0\54\0\u03c8\0\54\0\54\0\54\0\54\0\260"+
    "\0\u03f4\0\u0420\0\u0134\0\u044c\0\u0478\0\u04a4\0\54\0\u04d0"+
    "\0\u04fc\0\u0210\0\u0528\0\u0554\0\u0580\0\u0210\0\u05ac\0\u05d8"+
    "\0\u0604\0\u0630\0\54\0\u04d0\0\54\0\54\0\u065c\0\u0688"+
    "\0\u06b4\0\u0210\0\u0210\0\u06e0\0\u0210\0\u070c\0\u0210\0\u0210"+
    "\0\u0738\0\u0764\0\u0790\0\u0210\0\u0210\0\u0210";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[78];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\2\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\26\1\32\1\33\1\34\1\35\1\26\1\36"+
    "\3\26\1\37\1\26\1\40\1\26\1\41\1\42\1\43"+
    "\1\44\100\0\1\45\34\0\1\46\54\0\1\47\10\0"+
    "\2\50\5\0\2\50\2\0\17\50\22\0\2\51\51\0"+
    "\1\52\52\0\1\51\1\0\2\53\6\0\1\54\5\0"+
    "\1\54\33\0\1\51\1\0\2\20\6\0\1\54\5\0"+
    "\1\54\42\0\1\55\53\0\1\56\53\0\1\57\46\0"+
    "\2\26\5\0\2\26\2\0\17\26\15\0\1\60\1\0"+
    "\1\60\2\0\2\26\5\0\2\26\2\0\17\26\22\0"+
    "\2\26\5\0\2\26\2\0\5\26\1\61\11\26\22\0"+
    "\2\26\5\0\2\26\2\0\11\26\1\62\5\26\15\0"+
    "\1\60\1\0\1\60\2\0\2\26\5\0\2\26\2\0"+
    "\7\26\1\63\7\26\22\0\2\26\5\0\2\26\2\0"+
    "\7\26\1\64\1\26\1\65\5\26\22\0\2\26\5\0"+
    "\2\26\2\0\4\26\1\66\3\26\1\67\6\26\22\0"+
    "\2\26\5\0\2\26\2\0\13\26\1\70\3\26\22\0"+
    "\2\26\5\0\2\26\2\0\3\26\1\71\13\26\22\0"+
    "\2\26\5\0\2\26\2\0\5\26\1\72\11\26\55\0"+
    "\1\73\20\0\2\51\6\0\1\54\5\0\1\54\16\0"+
    "\2\52\2\0\50\52\12\0\1\60\1\0\1\60\2\0"+
    "\2\74\57\0\1\75\54\0\1\76\45\0\2\74\52\0"+
    "\2\26\5\0\2\26\2\0\1\77\16\26\22\0\2\26"+
    "\5\0\2\26\2\0\14\26\1\100\2\26\22\0\2\26"+
    "\5\0\2\26\2\0\11\26\1\101\5\26\22\0\2\26"+
    "\5\0\2\26\2\0\13\26\1\102\3\26\22\0\2\26"+
    "\5\0\2\26\2\0\15\26\1\103\1\26\22\0\2\26"+
    "\5\0\2\26\2\0\6\26\1\104\10\26\22\0\2\26"+
    "\5\0\2\26\2\0\15\26\1\105\1\26\22\0\2\26"+
    "\5\0\2\26\2\0\6\26\1\106\10\26\22\0\2\26"+
    "\5\0\2\26\2\0\13\26\1\107\3\26\22\0\2\26"+
    "\5\0\2\26\2\0\3\26\1\110\13\26\22\0\2\26"+
    "\5\0\2\26\2\0\1\111\16\26\22\0\2\26\5\0"+
    "\2\26\2\0\10\26\1\112\6\26\22\0\2\26\5\0"+
    "\2\26\2\0\7\26\1\113\7\26\22\0\2\26\5\0"+
    "\2\26\2\0\15\26\1\114\1\26\22\0\2\26\5\0"+
    "\2\26\2\0\15\26\1\115\1\26\22\0\2\26\5\0"+
    "\2\26\2\0\3\26\1\116\13\26\3\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1980];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\2\11\3\1\6\11\4\1\2\11\5\1\2\11"+
    "\10\1\1\11\1\1\4\11\1\0\2\1\2\0\2\1"+
    "\1\11\1\0\12\1\1\11\1\1\2\11\20\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[78];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new Error("Illegal character <"+yytext()+">");
            }
            // fall through
          case 41: break;
          case 2:
            { 
            }
            // fall through
          case 42: break;
          case 3:
            { return new Symbol(sym.LNE);
            }
            // fall through
          case 43: break;
          case 4:
            { return new Symbol(sym.AP);
            }
            // fall through
          case 44: break;
          case 5:
            { return new Symbol(sym.CP);
            }
            // fall through
          case 45: break;
          case 6:
            { return new Symbol(sym.POR);
            }
            // fall through
          case 46: break;
          case 7:
            { return new Symbol(sym.MAS);
            }
            // fall through
          case 47: break;
          case 8:
            { return new Symbol(sym.COMA);
            }
            // fall through
          case 48: break;
          case 9:
            { return new Symbol(sym.MENOS);
            }
            // fall through
          case 49: break;
          case 10:
            { return new Symbol(sym.DIV);
            }
            // fall through
          case 50: break;
          case 11:
            { return new Symbol(sym.NUMERO, yytext());
            }
            // fall through
          case 51: break;
          case 12:
            { return new Symbol(sym.PP);
            }
            // fall through
          case 52: break;
          case 13:
            { return new Symbol(sym.PYC);
            }
            // fall through
          case 53: break;
          case 14:
            { return new Symbol(sym.LME);
            }
            // fall through
          case 54: break;
          case 15:
            { return new Symbol(sym.ASIG);
            }
            // fall through
          case 55: break;
          case 16:
            { return new Symbol(sym.LMA);
            }
            // fall through
          case 56: break;
          case 17:
            { return new Symbol(sym.IDENT, yytext() );
            }
            // fall through
          case 57: break;
          case 18:
            { return new Symbol(sym.AB);
            }
            // fall through
          case 58: break;
          case 19:
            { return new Symbol(sym.CB);
            }
            // fall through
          case 59: break;
          case 20:
            { return new Symbol(sym.ALL);
            }
            // fall through
          case 60: break;
          case 21:
            { return new Symbol(sym.CLL);
            }
            // fall through
          case 61: break;
          case 22:
            { return new Symbol(sym.LNEQ);
            }
            // fall through
          case 62: break;
          case 23:
            { return new Symbol(sym.LAND);
            }
            // fall through
          case 63: break;
          case 24:
            { return new Symbol(sym.TEXTO, yytext().substring(1, yytext().length()-1));
            }
            // fall through
          case 64: break;
          case 25:
            { return new Symbol(sym.LMEQ);
            }
            // fall through
          case 65: break;
          case 26:
            { return new Symbol(sym.LEQ);
            }
            // fall through
          case 66: break;
          case 27:
            { return new Symbol(sym.LMAQ);
            }
            // fall through
          case 67: break;
          case 28:
            { return new Symbol(sym.DO);
            }
            // fall through
          case 68: break;
          case 29:
            { return new Symbol(sym.IF);
            }
            // fall through
          case 69: break;
          case 30:
            { return new Symbol(sym.LOR);
            }
            // fall through
          case 70: break;
          case 31:
            { return new Symbol(sym.ADD);
            }
            // fall through
          case 71: break;
          case 32:
            { return new Symbol(sym.DEL);
            }
            // fall through
          case 72: break;
          case 33:
            { return new Symbol(sym.FOR);
            }
            // fall through
          case 73: break;
          case 34:
            { return new Symbol(sym.INT,0);
            }
            // fall through
          case 74: break;
          case 35:
            { return new Symbol(sym.SET);
            }
            // fall through
          case 75: break;
          case 36:
            { return new Symbol(sym.CHAR,1);
            }
            // fall through
          case 76: break;
          case 37:
            { return new Symbol(sym.ELSE);
            }
            // fall through
          case 77: break;
          case 38:
            { return new Symbol(sym.FLOAT,2);
            }
            // fall through
          case 78: break;
          case 39:
            { return new Symbol(sym.PRINT);
            }
            // fall through
          case 79: break;
          case 40:
            { return new Symbol(sym.WHILE);
            }
            // fall through
          case 80: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
