
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENT = 3;
  public static final int MENOS = 4;
  public static final int CP = 9;
  public static final int POR = 6;
  public static final int EOF = 0;
  public static final int MAS = 5;
  public static final int NUMERO = 2;
  public static final int DIV = 7;
  public static final int error = 1;
  public static final int AP = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMERO",
  "IDENT",
  "MENOS",
  "MAS",
  "POR",
  "DIV",
  "AP",
  "CP"
  };
}

