
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 11;
  public static final int ELSE = 24;
  public static final int CP = 7;
  public static final int IDENT = 2;
  public static final int LNE = 20;
  public static final int PYC = 8;
  public static final int WHILE = 25;
  public static final int LOR = 22;
  public static final int ALL = 4;
  public static final int LNEQ = 15;
  public static final int LMAQ = 17;
  public static final int CLL = 5;
  public static final int IF = 23;
  public static final int LAND = 21;
  public static final int POR = 12;
  public static final int AP = 6;
  public static final int DO = 26;
  public static final int EOF = 0;
  public static final int DIV = 13;
  public static final int LMEQ = 19;
  public static final int PRINT = 28;
  public static final int error = 1;
  public static final int NUMERO = 3;
  public static final int LME = 18;
  public static final int LEQ = 14;
  public static final int FOR = 27;
  public static final int LMA = 16;
  public static final int ASIG = 9;
  public static final int MAS = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENT",
  "NUMERO",
  "ALL",
  "CLL",
  "AP",
  "CP",
  "PYC",
  "ASIG",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "LEQ",
  "LNEQ",
  "LMA",
  "LMAQ",
  "LME",
  "LMEQ",
  "LNE",
  "LAND",
  "LOR",
  "IF",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "PRINT"
  };
}

