
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 13;
  public static final int IDENT = 21;
  public static final int CP = 6;
  public static final int PYC = 10;
  public static final int CONCATENA = 16;
  public static final int MATRIZ = 22;
  public static final int ALL = 3;
  public static final int TRANSPUESTA = 18;
  public static final int INVERSA = 17;
  public static final int CLL = 4;
  public static final int UMENOS = 2;
  public static final int CC = 8;
  public static final int POR = 14;
  public static final int AP = 5;
  public static final int COMA = 9;
  public static final int EOF = 0;
  public static final int VECTOR = 23;
  public static final int DIV = 15;
  public static final int ADJUNTA = 19;
  public static final int AC = 7;
  public static final int NUMERO = 24;
  public static final int PRINT = 20;
  public static final int error = 1;
  public static final int ASIG = 11;
  public static final int MAS = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "UMENOS",
  "ALL",
  "CLL",
  "AP",
  "CP",
  "AC",
  "CC",
  "COMA",
  "PYC",
  "ASIG",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "CONCATENA",
  "INVERSA",
  "TRANSPUESTA",
  "ADJUNTA",
  "PRINT",
  "IDENT",
  "MATRIZ",
  "VECTOR",
  "NUMERO"
  };
}

